=== shukun-ai/truo/libs/schema/src/json-schemas/application.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "ApplicationSchema",
  "description": "Describe a Shukun Application",
  "type": "object",
  "additionalProperties": false,
  "required": ["title"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "metadata": {
      "type": "array",
      "items": {
        "$ref": "metadata.schema.json"
      }
    },
    "views": {
      "type": "array",
      "items": {
        "$ref": "view.schema.json"
      }
    },
    "workflows": {
      "type": "array",
      "items": {
        "$ref": "workflow.schema.json"
      }
    },
    "flows": {
      "type": "array",
      "items": {
        "$ref": "flow.schema.json"
      }
    },
    "roles": {
      "type": "array",
      "items": {
        "$ref": "role.schema.json"
      }
    },
    "schedules": {
      "type": "array",
      "items": {
        "$ref": "schedule.schema.json"
      }
    }
  }
}

=== shukun-ai/truo/libs/schema/src/validators/application/application.test.json
{
  "$schema": "../../json-schemas/application.schema.json",
  "title": "Mock Application",
  "description": "Mock Application for SKP",
  "metadata": [
    {
      "name": "product_categories",
      "label": "商品分类",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "displayName"
        },
        {
          "name": "label",
          "label": "分类名称",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": true
        },
        {
          "name": "priority",
          "label": "排序",
          "fieldType": "Integer",
          "isRequired": true,
          "isIndexed": true
        },
        {
          "name": "visible",
          "label": "是否显示",
          "fieldType": "Boolean",
          "isRequired": true
        },
        {
          "name": "menu",
          "label": "上级分类",
          "fieldType": "ManyToOne",
          "isRequired": true,
          "referenceTo": "menu_categories",
          "foreignName": "label",
          "isIndexed": true
        },
        {
          "name": "cover",
          "label": "封面图片",
          "fieldType": "Attachment",
          "isRequired": true
        }
      ]
    },
    {
      "name": "system__roles",
      "label": "角色",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "displayName"
        },
        {
          "name": "name",
          "label": "角色 ID 名",
          "fieldType": "NameText",
          "isRequired": true,
          "isUnique": true,
          "isIndexed": true
        },
        {
          "name": "label",
          "label": "角色显示名",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false
        },
        {
          "name": "permissions",
          "label": "权限清单",
          "fieldType": "Mixed",
          "isRequired": true
        }
      ]
    },
    {
      "name": "orders",
      "label": "订单",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "displayName"
        },
        {
          "name": "number",
          "label": "订单编号",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": true
        },
        {
          "name": "payStatus",
          "label": "支付状态",
          "fieldType": "SingleSelect",
          "isRequired": true,
          "options": [
            {
              "key": "unpaid",
              "label": "未支付"
            },
            {
              "key": "paid",
              "label": "已支付"
            }
          ]
        },
        {
          "name": "payment",
          "label": "支付方式",
          "fieldType": "SingleSelect",
          "isRequired": false,
          "options": [
            {
              "key": "pay",
              "label": "支付"
            }
          ]
        },
        {
          "name": "orderStatus",
          "label": "订单状态",
          "fieldType": "SingleSelect",
          "isRequired": true,
          "options": [
            {
              "key": "created",
              "label": "已创建订单"
            },
            {
              "key": "waitDelivered",
              "label": "等待发货"
            },
            {
              "key": "waitReceived",
              "label": "等待收货"
            },
            {
              "key": "waitFinished",
              "label": "等待完成"
            },
            {
              "key": "finished",
              "label": "已完成"
            },
            {
              "key": "canceled",
              "label": "已取消"
            }
          ]
        },
        {
          "name": "consignee",
          "label": "收件人",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "phone",
          "label": "联系号码",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "address",
          "label": "详细地址",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "postcode",
          "label": "邮编",
          "fieldType": "Text",
          "isRequired": false,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "comment",
          "label": "备注",
          "fieldType": "Text",
          "isRequired": false,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "totalOriginAmount",
          "label": "原总价",
          "fieldType": "Currency",
          "isRequired": true,
          "currencyOptions": {
            "code": "CNY",
            "scale": 2
          }
        },
        {
          "name": "totalOffAmount",
          "label": "优惠的总价",
          "fieldType": "Currency",
          "isRequired": true,
          "currencyOptions": {
            "code": "CNY",
            "scale": 2
          }
        },
        {
          "name": "totalPaidAmount",
          "label": "实付总价",
          "fieldType": "Currency",
          "isRequired": true,
          "currencyOptions": {
            "code": "CNY",
            "scale": 2
          }
        }
      ]
    },
    {
      "name": "order_products",
      "label": "订单商品",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "displayName"
        },
        {
          "name": "product",
          "label": "关联商品",
          "fieldType": "ManyToOne",
          "isRequired": true,
          "referenceTo": "products",
          "foreignName": "label",
          "isIndexed": false
        },
        {
          "name": "order",
          "label": "关联订单",
          "fieldType": "ManyToOne",
          "isRequired": true,
          "referenceTo": "orders",
          "foreignName": "number",
          "isIndexed": true
        },
        {
          "name": "label",
          "label": "关联商品名称",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "stockSnapshot",
          "label": "库存快照",
          "fieldType": "Integer",
          "isRequired": true,
          "isIndexed": false
        },
        {
          "name": "priceSnapshot",
          "label": "价格快照",
          "fieldType": "Currency",
          "isRequired": true,
          "currencyOptions": {
            "code": "CNY",
            "scale": 2
          }
        },
        {
          "name": "quality",
          "label": "购买数量",
          "fieldType": "Integer",
          "isRequired": true,
          "isIndexed": false
        }
      ]
    },
    {
      "name": "system__workflows",
      "label": "工作流",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "username"
        },
        {
          "name": "name",
          "label": "工作流 ID 名",
          "fieldType": "NameText",
          "isRequired": true,
          "isUnique": true
        },
        {
          "name": "description",
          "label": "描述",
          "fieldType": "Text",
          "isRequired": false
        },
        {
          "name": "configurations",
          "label": "配置",
          "fieldType": "Mixed",
          "isRequired": false
        },
        {
          "name": "validations",
          "label": "请求验证条件",
          "fieldType": "Mixed",
          "isRequired": false
        },
        {
          "name": "isEnabledWebhook",
          "label": "允许接口访问",
          "fieldType": "Boolean",
          "isRequired": false
        }
      ]
    },
    {
      "name": "stock_logs",
      "label": "库存变更记录",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "username"
        },
        {
          "name": "summary",
          "label": "描述",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": false
        },
        {
          "name": "product",
          "label": "所属产品",
          "fieldType": "ManyToOne",
          "isRequired": true,
          "referenceTo": "products",
          "foreignName": "label",
          "isIndexed": false
        },
        {
          "name": "stock",
          "label": "库存变化量",
          "fieldType": "Integer",
          "isRequired": true,
          "isIndexed": false
        }
      ]
    },
    {
      "name": "products",
      "label": "商品",
      "electrons": [
        {
          "name": "owner",
          "label": "创建人",
          "fieldType": "Owner",
          "isRequired": false,
          "referenceTo": "system__users",
          "foreignName": "username"
        },
        {
          "name": "label",
          "label": "商品名称",
          "fieldType": "Text",
          "isRequired": true,
          "isUnique": false,
          "isIndexed": true
        },
        {
          "name": "categories",
          "label": "分类",
          "fieldType": "ManyToMany",
          "isRequired": true,
          "referenceTo": "product_categories",
