=== shukun-ai/truo/libs/schema/src/json-schemas/workflow.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "WorkflowSchema",
  "description": "Describe Workflow Schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["name"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "format": "apiName"
    },
    "description": {
      "type": "string"
    },
    "isEnabledWebhook": {
      "type": "boolean"
    },
    "validations": {},
    "configurations": {
      "$ref": "workflows/configurations.schema.json"
    }
  }
}

=== shukun-ai/truo/libs/cli/src/__mock__/input/workflows/test.json
{
  "$schema": "../../../../node_modules/@shukun/schema/src/json-schemas/application/workflow.schema.json",
  "name": "test",
  "description": "测试",
  "configurations": {
    "startAt": "createOrder",
    "states": {
      "createOrder": {
        "type": "Task",
        "resource": "code:js",
        "parameters": {
          "code": "{{code:test}}",
          "hello.$": "$.body.hello"
        },
        "end": true,
        "resultPath": "$.test",
        "outputPath": "$.test",
        "x": -100,
        "y": 280
      }
    },
    "startX": 0,
    "startY": 180
  },
  "validations": {
    "type": "object",
    "required": ["hello"],
    "properties": {
      "hello": {
        "type": "string"
      }
    }
  },
  "isEnabledWebhook": true
}
