=== shukun-ai/truo/libs/schema/src/json-schemas/reference/reference-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "ReferenceDataSchema",
  "definitions": {
    "schemaArray": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#"
      }
    },
    "simpleTypes": {
      "enum": [
        "array",
        "boolean",
        "integer",
        "null",
        "number",
        "object",
        "string"
      ]
    },
    "stringArray": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "default": []
    }
  },
  "type": ["boolean", "object"],
  "properties": {
    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "items": {
      "anyOf": [
        {
          "$ref": "#"
        },
        {
          "$ref": "#/definitions/schemaArray"
        }
      ],
      "default": true
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "additionalProperties": {
      "$ref": "#"
    },
    "definitions": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "properties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "default": {}
    },
    "patternProperties": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#"
      },
      "propertyNames": {
        "format": "regex"
      },
      "default": {}
    },
    "const": true,
    "enum": {
      "type": "array",
      "items": true,
      "minItems": 1,
      "uniqueItems": true
    },
    "type": {
      "$ref": "#/definitions/simpleTypes"
    }
  },
  "default": {}
}

=== shukun-ai/truo/libs/schema/src/json-schemas/flow-compiled-codes.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "FlowCompiledCodes",
  "description": "Describe Flow Compiled Codes",
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^(\\w)+$": {
      "title": "FlowOrgCompiledCodes",
      "type": "object",
      "patternProperties": {
        "^(\\w)+$": {
          "title": "FlowEventCompiledCodes",
          "type": "object",
          "patternProperties": {
            "^(\\w)+$": {
              "title": "FlowEventCompiledCode",
              "type": "string"
            }
          }
        }
      }
    }
  }
}
