=== shukun-ai/truo/libs/schema/src/json-schemas/application/flow.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "FlowSchema",
  "description": "Describe Flow Schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["name", "input", "output", "startEventName", "events", "store"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "format": "apiName"
    },
    "description": {
      "type": "string"
    },
    "input": {
      "type": "object",
      "description": "The input JSON Schema Rule"
    },
    "output": {
      "type": "object",
      "description": "The output JSON Schema Rule"
    },
    "startEventName": {
      "type": "string"
    },
    "events": {
      "$ref": "flow/events.schema.json"
    },
    "store": {
      "$ref": "flow/store.schema.json"
    }
  }
}

=== shukun-ai/truo/libs/cli/src/__mock__/input/flows/apply_revoke_departure_task.json
{
  "$schema": "../../../../node_modules/@shukun/schema/src/json-schemas/application/flow.schema.json",
  "name": "apply_revoke_departure_task",
  "input": {},
  "output": {},
  "store": {},
  "startEventName": "saveParameters",
  "events": {
    "saveParameters": {
      "next": "findOneTask",
      "key": "parameters",
      "value": "{taskId: \"$.input.taskId\", vehicleId: \"$.input.vehicleId\"}",
      "type": "Store"
    },
    "findOneTask": {
      "next": "checkQueueExist",
      "atomName": "departure_tasks",
      "query": {
        "filter": {
          "_id": {
            "$eq": "$.store.parameters.taskId"
          },
          "vehicle": {
            "$eq": "$.store.parameters.vehicleId"
          },
          "status": {
            "$in": "['accepted']"
          }
        },
        "select": {
          "_id": true,
          "vehicle": true
        }
      },
      "type": "SourceQuery"
    },
    "checkQueueExist": {
      "next": "createNewQueue",
      "conditions": [
        {
          "condition": "$.input.length !== 0 && $.input[0].appliedVehicle === $.store.parameters.vehicleId",
          "next": "returnExist"
        }
      ],
      "type": "Choice"
    },
    "returnExist": {
      "type": "Success",
      "output": "{ _id: $.input[0]['_id'] }"
    },
    "return": {
      "output": "$.input",
      "type": "Success"
    },
    "createNewQueue": {
      "next": "return",
      "atomName": "revoke_departure_tasks_queue",
      "data": {
        "departureTask": "$.store.parameters.taskId",
        "appliedVehicle": "$.store.parameters.vehicleId"
      },
      "type": "SourceCreate"
    }
  }
}
